//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyecto.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class USUARIO
    {
        public int USUARIO_ID { get; set; }
        public string USUARIO_CODIGO { get; set; }
        public string USUARIO_EMAIL { get; set; }
        public string USUARIO_PASSWORD { get; set; }
        public Nullable<int> ROL_ID { get; set; }
        public Nullable<bool> ESTADO { get; set; }
        public Nullable<bool> CAMBIO_PASSWORD { get; set; }
        public Nullable<int> INTENTOS_AUTENTICACION { get; set; }
    
        public virtual ROL ROL { get; set; }
    }
}
